### ISSUE TITLE
Accessing Homekit with multiple Devices

### ISSUE THREAD

**Issue by dermarder** [michbeck100/pimatic-hap#11]
Hey,

first of all great work!
Unfortunately im having a problem. Im only able to connect with one iDevice at the same time.
Ive got a iPhone and an iPad but i am can only connect with one device.
The other device has access to the homekit but the devices are all unreachable.

Any help would be awesome.
Sorry for my bad language.

thanks in advance,

Tom

**Comment by michbeck100** [comment]
I think you have to invite other people to share your homekit devices. I'm not sure how to share if the devices use the same Apple ID

**Comment by michbeck100** [comment]
Seems that iOS 9 prevents you from doing this: https://github.com/nfarina/homebridge/issues/119

**Comment by rspaargaren** [comment]
I have the EVE app on multiple devices running! You install it on one of the apple device and than you share your environment with others. They will receive a link where your homekit environment is shared. Eve uses this configuration on the device. You have to enable Keychain in icloud to actually use the EVE app.

**Comment by michbeck100** [comment]
Thanks for your help, this should help.

**Comment by dermarder** [comment]
Thank you for your help. So i have to go to Settings -> HomeKit 
And use the Share Option to Send the config to my other device?

**Comment by rspaargaren** [comment]
In eve you can go to "guest access" in EVE there you can invite somebody via email.
At the invited device they will add your home configuration to homekit.
Maybe you can do it also directly in homekit settings in the apple menu.
