### ISSUE TITLE
Add Humidity sensors

### ISSUE THREAD

**Issue by tjandt** [michbeck100/pimatic-hap#12]
I have some humidity sensors attached to my pimatic. How could these be exposed to homekit?

**Comment by michbeck100** [comment]
What plugin are you using to connect the sensors? I would have a look if its possible to add support.

**Comment by tjandt** [comment]
I'm using pimatic-dht-sensors ... Temperature is working fine only Humidity is missing at the moment. If I could help you feel free to get in touch.

**Comment by michbeck100** [comment]
pimatic-dht-sensors is misusing the TemperatureSensor class. A TemperatureSensor from pimatic doesn't support humidity, only temperature. Since pimatic-hap currently just supports the features of the base class, measuring humidity would require a rewrite of the dht sensors plugin.

**Comment by tjandt** [comment]
So I should get in contact with the developer of https://github.com/pimatic/pimatic-dht-sensors ?

**Comment by michbeck100** [comment]
You could also create a fork of the plugin and make the changes by yourself. Then submit a pull request. Maybe I'll find the time to make the changes, but i don't have any device to test.

**Comment by tjandt** [comment]
Which class should be used? Or should I create a new HumiditySensor class? Just to understand which information is needed that you plugin can expose this humidity information via HomeKit

**Comment by michbeck100** [comment]
HomeKit itself does differentiate between temperature sensor and humidity sensor. One solution would be to create a new device class, the other way would be, to change the way pimatic-hap recognizes device capabilities. I have to think about this, but it's probably easier to go for the second way, since there are more plugins out there that use the same way to measure humidity

**Comment by tjandt** [comment]
okay so if I should test something or if you need something we can use my setup.
 I'll try to support you as good as possible ;)

**Comment by rspaargaren** [comment]
I can do the same, I was already exloring your code and the related hap-nodeJS code. As I have more devices also a PIR device. But I have to learn more on the basics of java, koffie, promise etc....

**Comment by michbeck100** [comment]
Should be working with the next release ;-)

**Comment by tjandt** [comment]
cool ... I'll give it a try after christmas ;) thanks for your work
