### ISSUE TITLE
Cannot find accesory

### ISSUE THREAD

**Issue by rspaargaren** [michbeck100/pimatic-hap#13]
Hi,

I have updated to the latest version by removing all the files and the hap database but somehow I am not able to find the pimatic via eve. I have removed the homekit also from my Phone.
How can I debug it? Somebody else having the same issue?

**Comment by rspaargaren** [comment]
Looks like it is an issue on my iPhone. My IPad is able to connect....But what to do now? tried deleting the app, removing the settings, etc. Any ideas?

**Comment by michbeck100** [comment]
As I don't have more than one device to test, I'm not sure, but I think you can just connect with one device at a time. 
Maybe the issue is that your iPad is already connected?
Otherwise just remove all HomeKit related settings.

**Comment by rspaargaren** [comment]
Hi i have succeded to reconnect my iPhone again after resetting the HomeKit settings in the privacy tab as well. However this morning I was not able to reconnect with the phone ...?

**Comment by michbeck100** [comment]
This is kind of a known issue, but I can't tell what the reason is, yet. One solution is, starting pimatic in daemon mode. Another one, sometimes the network is an issue. 
Unfortunately this error doesn't come from the plugin itself, but from the dependency that implements the HomeKit connectivity.

**Comment by rspaargaren** [comment]
At the moment it is running in daemon mode. But I did a manual install via Sudo npm pimatic-hap could that be the clause. Your source on git hub looks newer that the one installed? My version is now 4.1

**Comment by michbeck100** [comment]
if you have problems with the HEAD branch of the plugin just use the official version. The easiest way is to delete pimatic-hap from node_modules, hap-database from pimatic root dir and then restart pimatic.
