### ISSUE TITLE
How to change color via siri

### ISSUE THREAD

**Issue by Xento** [michbeck100/pimatic-hap#15]
Does changing the color over siri work?
What command do I have to use?

**Comment by michbeck100** [comment]
Haven't tried, yet, but this link provides some examples if German is your language: 
http://markus-jasinski.de/2015/11/erste-erfahrungen-mit-homekit/

**Comment by thymian** [comment]
Hey, i just talked to siri like an hour to make her switch the colors, but she still doesnt want to.
:white_check_mark: Switching on/off via siri works
:white_check_mark: changing the brightness via siri works
:white_check_mark: changing the color VIA EVE works
:no_entry_sign: changing the color via siri doesnt work
See Picture:
[Click Me](https://cloud.githubusercontent.com/assets/10746167/12116781/88f18d3c-b3bc-11e5-8ea5-236fa3335759.png)

**Comment by michbeck100** [comment]
Found the problem, the characteristic for saturation is not set. Since i don't really like the color handling i've implemented, i will have to change this anyways. Then i will fix this issue, too.

**Comment by Xento** [comment]
This pullrequest https://github.com/michbeck100/pimatic-hap/pull/17 fixes the issue with siri ;-)

**Comment by michbeck100** [comment]
Thanks for the PR but i had some other changes regarding colors, too, so i don't need the PR anymore.
