### ISSUE TITLE
Rollladen wird in Eve als schloss angezeigt 

### ISSUE THREAD

**Issue by seelenbrokat** [michbeck100/pimatic-hap#21]
Steht eigentlich alles schon in der Überschrift.:-) denke das Thema wird erledigt sein sobald die Geräte selber konfigurierbar sind. Oder?

**Comment by michbeck100** [comment]
In english, please. No it won't. The implementation in pimatic knows just close and open whereas HomeKit has more sophisticated states for shutters. This is why I implemented shutters as locks. This was the first shot. Once I got time for this I might implement  a more intelligent solution

**Comment by michbeck100** [comment]
I did change the implementation from Service.LockMechanism to Service.GarageDoorOpener. This has almost the same features like the pimatic shutter. And it doesn't look like a lock.
