### ISSUE TITLE
Temperature Minimum is 0.0 Degrees

### ISSUE THREAD

**Issue by l0mp1** [michbeck100/pimatic-hap#22]
My outside temperature sensor (GT-WT-02) is measuring -7.6 degrees Celsius right now. This is also displayed in the log and in the pimatic frontend. However, Eve is showing 0.0 degrees Celsius. 
Temperature values seem to be displayed correctly when >= 0.0 degrees.

Log:
21:24:24.072 [pimatic-homeduino] debug: weather12:  { id: 43,
21:24:24.072 [pimatic-homeduino] debug:>  channel: 1,
21:24:24.072 [pimatic-homeduino] debug:>  temperature: -7.6,
21:24:24.072 [pimatic-homeduino] debug:>  humidity: 89,
21:24:24.072 [pimatic-homeduino] debug:>  lowBattery: false }

**Comment by michbeck100** [comment]
Already fixed since 962cae4

**Comment by michbeck100** [comment]
I hope a min temperature of -50 degrees is enough...
