### ISSUE TITLE
Exclude devices from HomeKit

### ISSUE THREAD

**Issue by Frederick-G764** [michbeck100/pimatic-hap#23]
Hi,

it would be great to exclude specific devices from homekit.

PS. Thank you very much for this amazing plugin :)

**Comment by michbeck100** [comment]
Currently I'm working on enhancing the device configuration to override the service type (#20). I will add an option to disable devices, too.

**Comment by michbeck100** [comment]
please see the README.md for instructions how to exclude the devices.
