### ISSUE TITLE
Slidings back dimmers?

### ISSUE THREAD

**Issue by rspaargaren** [michbeck100/pimatic-hap#25]
My dimmers now seam to slide back to 0 after setting the value but they keep burning. This is both in pimatic and in eve. It looks like some interference between both pimatic-hap and the core? Does anybody else has this behaviour. I have juist update everyting to the latent official releases. No github yet for hap.

**Comment by rspaargaren** [comment]
What info do you require from the config.json? Basically I have a HomeduinoRFDimmer which has this behaviour.

**Comment by michbeck100** [comment]
More detailed instructions on how to reproduce the error would be great. e.g. how do you change the value, via Siri or pimatic directly.

**Comment by rspaargaren** [comment]
Unfortunately I can not make an animation of it. But basically the behaviour is as follows: Witin Pimatic I slide the dimming value to a certain value. It gives me a indication the level is set at the value. The light is actually set at the value and after that the slider moves back to the zero position but the light stays at the set level. This happens both within pimatic and in Eve. Via Siri (voice) I have not tried. The behaviour was introduced after upgrading to the latest versions. Not other changes in the config.

**Comment by michbeck100** [comment]
Ok, i'll try to reproduce this behavior. Do you have any additional rules in your config.json regarding the dimmers?

**Comment by rspaargaren** [comment]
One of the dimmer has rule attached that it will dimm to a certain value after activation of the PIR for a certain time. Then the slider has the same behaviour. If I have a look in the event log I see three entries at the same time: Lamp - Dimlevel 52% - Lamp State On - Lamp Dimlevel 1% When activated by PIR lamp dimlevel 100% and imediately after 2%. When sliding back to 0 the log is Lamp - Dimlevel 0% Lamp State off

**Comment by michbeck100** [comment]
I couldn't reproduce the error on my side yet. Do you have debug messages enabled? If not please do it, and post the log messages when you start sliding the dimmer.

**Comment by rspaargaren** [comment]
How do I enable the debug messages for the hap plug-in? I see debug message from the boot sequence but.not from the actual switch with pimatic?

**Comment by michbeck100** [comment]
just look at pimatic-daemon.log and search for

```
[pimatic-hap] publishing homekit bridge on port
```

then you know debug is enabled. You should see loads of messages from pimatic-hap in the log file when using eve. Every access to the homekit bridge by eve is logged with debug level.

**Comment by rspaargaren** [comment]
I have started my configuration manually in the following way but not debug messages in the console:
sudo DEBUG=HAPServer,EventedHTTPServer,Accessory node node_modules/pimatic/pimatic.js
What am I doing wrong?

**Comment by michbeck100** [comment]
This way of starting pimatic is outdated. just use the default way as described in http://pimatic.org/guide/getting-started/autostarting/

**Comment by michbeck100** [comment]
Whats the current state of this issue? Do you have any news?

**Comment by rspaargaren** [comment]
Hi, I have been busy so I could not test. Unfortunately I do see debug messages in my database in Pimatic but they are not written into the logfile. The latest action was to reinstall Pimatic-Hap and to update Pimatic core. But unfortunately that did not help. Could you indicate how to get the debug messages into the debug file.

**Comment by michbeck100** [comment]
I'm currently working on a new release which hopefully fixes this issue (and #29). If you want to try just use the current HEAD

**Comment by rspaargaren** [comment]
I have manually installed the latest github version. But unfortunately it is not a working version for me. Did I do anything wrong. The dimmer was sliding in al directions after setting it to a value. Now back to the lastest "normal" version.

**Comment by michbeck100** [comment]
Could you post your config? the devices and rules section would be interesting. And do you maybe remember with which version of pimatic-hap this issue arose?

**Comment by rspaargaren** [comment]
I dont know at wat version the behavior started.

I finally have some part of the debug log

22:06:21debug [pimatic-hap]: [Pimatic HomeKit Bridge] Setting Characteristic "Brightness" to value 79
22:06:21debug [pimatic-hap]: [Pimatic HomeKit Bridge] Processing characteristic set: [{"aid":4,"iid":15,"value":79}]
22:06:21debug [pimatic-hap]: [fa:fe:db:e4:36:2c] HAP Request: PUT /characteristics
22:06:20debug [pimatic-hap]: [Pimatic HomeKit Bridge] Setting Characteristic "Brightness" to value 8
22:06:20debug [pimatic-hap]: [Pimatic HomeKit Bridge] Processing characteristic set: [{"aid":4,"iid":15,"value":8}]
22:06:20debug [pimatic-hap]: [fa:fe:db:e4:36:2c] HAP Request: PUT /characteristics
22:06:10debug [pimatic-hap]: [Pimatic HomeKit Bridge] Setting Characteristic "Brightness" to value 69
22:06:10debug [pimatic-hap]: [Pimatic HomeKit Bridge] Processing characteristic set: [{"aid":4,"iid":15,"value":69}]
22:06:10debug [pimatic-hap]: [fa:fe:db:e4:36:2c] HAP Request: PUT /characteristics
22:06:09debug [pimatic-hap]: [Pimatic HomeKit Bridge] Setting Characteristic "Brightness" to value 7
22:06:09debug [pimatic-hap]: [Pimatic HomeKit Bridge] Processing characteristic set: [{"aid":4,"iid":15,"value":7}]
22:06:09debug [pimatic-hap]: [fa:fe:db:e4:36:2c] HAP Request: PUT /characteristics

**Comment by rspaargaren** [comment]
I did a bit of debugging and I don't think it is the hap plugin.. I have removed the plugin from the config file and still the same behaviour.... Now I suspect the homeduino .... Could it be that it picks up one of the last repeats as a dim signal? See debug? I know this is not the right place to ask ...

2016-04-17 22:50:52debug [pimatic-homeduino]: dimmer1:  { id: 1337110, all: false, unit: 0, dimlevel: 9, state: undefined }
22:50:52debug [pimatic-homeduino]: received: [ 220, 340, 1269, 2640, 10416 ] 1310121012101210121012121010121210101210121012121012101012111212101210121010121012101212101012121012101012111210101012101210121012121010121012121014
22:50:52debug [pimatic-homeduino]: data: "RF receive 340 2640 220 1269 10416 0 0 0 0102030203020302030203030202030302020302030203030203020203000303020302030202030203020303020203030203020203000302020203020302030203030202030203030204"
22:50:52debug [pimatic-homeduino]: data: "ACK"
22:50:51debug [pimatic-homeduino]: Sending Protocol: dimmer1 id:1337110 unit:0 all:false dimlevel:9 Pin:4 Repeats:7

**Comment by michbeck100** [comment]
You're right, this is not the right place ;-). Just create an issue in the pimatic-homeduino project or on the pimatic forum.
