### ISSUE TITLE
Support Philips hue devices from pimatic-hue-zll

### ISSUE THREAD

**Issue by michbeck100** [michbeck100/pimatic-hap#27]

**Comment by thexperiments** [comment]
Also highly anticipated by me

**Comment by michbeck100** [comment]
3faa7090fd009c56054e4907adb5bc49c85dd2c5 adds first implementation. 
@thexperiments Could you try to checkout the pimatic-hue-zll branch and test for me? I don't have any hue devices to test...

**Comment by thexperiments** [comment]
@michbeck100 wanted to try it out but I only have HueZLLExtendedColorLight in my setup. Maybe you could add it with just the dimming functionality

**Comment by michbeck100** [comment]
@thexperiments done and released as official release 0.7.0
