### ISSUE TITLE
Support for Bluetooth Smart-Technologie

### ISSUE THREAD

**Issue by ikewestbrook** [michbeck100/pimatic-hap#28]
Hi, it would be nice to also see bluettooth smart devices like Elgato Eve Room as devices. Any Chance? Thanks!

**Comment by michbeck100** [comment]
As far as I can tell Elgato's Eve Room is already certified for HomeKit and therefor there's no need to support this with pimatic-hap. You are probably thinking of the other way, showing these devices in pimatic? That's not the purpose of this plugin. Please ask for this feature at the pimatic repo at https://github.com/pimatic/pimatic
