### ISSUE TITLE
Pimatic-hap form outside the Wifi

### ISSUE THREAD

**Issue by fototeddy** [michbeck100/pimatic-hap#34]
Hello, i'm using piratic-hap for several weeks now. it works fine. I also own an apple TV3 and at the beginning it worked as HomeKit Bridge to control home kit form outside my home but now i need to be connected with my iPhone to the same wifi as my pimatic to control over homekit.
somebody know what to do to get it working again from outside?

**Comment by michbeck100** [comment]
I'm not using an Apple TV. And from outside of my home network I'm happy with using the pimatic mobile frontend. You should ask your question on the pimatic forum as there will probably be more people having faced the same issue. Just to be sure: you don't have this problem since 0.6.4, right?

**Comment by thexperiments** [comment]
For reference the solution from the forums also here.

What I did to get it working.
1. Privacy (Datenschutz) --> Homekit --> Reset Homekit-Configuration (!! be aware that everything homekit related you have set up will be removed)
2. delete the hap-database folder in your pimatic setup to also clear the association with the just cleared iOS configuration
3. Use EVE app to add your pimatic homekit bridge and set up rooms etc to your liking.
4. Make sure your iPhone is signed into iCloud and iCloud-Keychain is active (Schlüsselbund)
5. Restart your iPhone (should not really be necessary but hopefully forces a re-sync of iCloud keychain)
6. Sign out of iCloud with your Apple TV
7. Reboot Apple TV
8. Sign into iCloud with your Apple TV (exactly the same email address as your iPhone)
9. Restart your Apple TV (should not really be necessary but hopefully forces a re-sync of iCloud keychain)

**Make sure you have only one Home set up!! I had a second location shared via iCloud which broke the whole system again. This still seems very buggy.**
