### ISSUE TITLE
Installing Plugin pimatic-hap under v0.9.25

### ISSUE THREAD

**Issue by HarrySteff** [michbeck100/pimatic-hap#38]
When trying to instal pimatic-hap under newest pimatic version, i get the following output in Logfile:
`11:25:52.790 [pimatic] info: Installing: "pimatic-hap@0.7.0" from npm-registry.
11:25:56.186 [pimatic, ppm] info: WARN peerDependencies The pimatic plugin pimatic-hap is maybe not compatible with your pimatic version.
11:26:17.776 [pimatic, ppm] info: > curve25519@1.1.0 install /home/pi/pimatic-app/node_modules/pimatic-hap/node_modules/hap-nodejs/node_modules/curve25519
11:26:17.779 [pimatic, ppm] info: > node-gyp rebuild
11:26:22.470 [pimatic, ppm] info: make: Entering directory '/home/pi/pimatic-app/node_modules/pimatic-hap/node_modules/hap-nodejs/node_modules/curve25519/build'
11:26:22.488 [pimatic, ppm] info:   CXX(target) Release/obj.target/curve/node_curve.o
11:27:10.338 [pimatic, ppm] info:   SOLINK_MODULE(target) Release/obj.target/curve.node
11:27:10.791 [pimatic, ppm] info:   COPY Release/curve.node
11:27:10.829 [pimatic, ppm] info: make: Leaving directory '/home/pi/pimatic-app/node_modules/pimatic-hap/node_modules/hap-nodejs/node_modules/curve25519/build'
11:27:11.003 [pimatic, ppm] info: > ed25519@0.0.3 install /home/pi/pimatic-app/node_modules/pimatic-hap/node_modules/hap-nodejs/node_modules/ed25519
11:27:11.010 [pimatic, ppm] info: > node-gyp rebuild
11:27:14.649 [pimatic, ppm] info: make: Entering directory '/home/pi/pimatic-app/node_modules/pimatic-hap/node_modules/hap-nodejs/node_modules/ed25519/build'
11:27:14.654 [pimatic, ppm] info:   CC(target) Release/obj.target/ed25519/src/ed25519/keypair.o
11:27:19.234 [pimatic, ppm] info:   CC(target) Release/obj.target/ed25519/src/ed25519/sign.o
11:27:38.399 [pimatic, ppm] info:   CC(target) Release/obj.target/ed25519/src/ed25519/open.o
11:27:47.170 [pimatic, ppm] info:   CC(target) Release/obj.target/ed25519/src/ed25519/crypto_verify_32.o
11:28:08.174 [pimatic, ppm] info:   CC(target) Release/obj.target/ed25519/src/ed25519/ge_double_scalarmult.o
11:28:08.852 [pimatic, ppm] info:   CC(target) Release/obj.target/ed25519/src/ed25519/ge_frombytes.o
11:28:09.850 [pimatic, ppm] info:   CC(target) Release/obj.target/ed25519/src/ed25519/ge_scalarmult_base.o
11:28:17.876 [pimatic, ppm] info:   CC(target) Release/obj.target/ed25519/src/ed25519/ge_precomp_0.o
11:28:26.361 [pimatic, ppm] info:   CC(target) Release/obj.target/ed25519/src/ed25519/ge_p2_0.o
11:28:37.722 [pimatic, ppm] info:   CC(target) Release/obj.target/ed25519/src/ed25519/ge_p2_dbl.o
11:28:37.874 [pimatic, ppm] info:   CC(target) Release/obj.target/ed25519/src/ed25519/ge_p3_0.o
11:28:39.472 [pimatic, ppm] info:   CC(target) Release/obj.target/ed25519/src/ed25519/ge_p3_dbl.o
11:28:39.720 [pimatic, ppm] info:   CC(target) Release/obj.target/ed25519/src/ed25519/ge_p3_to_p2.o
11:28:39.964 [pimatic, ppm] info:   CC(target) Release/obj.target/ed25519/src/ed25519/ge_p3_to_cached.o
11:28:40.229 [pimatic, ppm] info:   CC(target) Release/obj.target/ed25519/src/ed25519/ge_p3_tobytes.o
11:28:40.485 [pimatic, ppm] info:   CC(target) Release/obj.target/ed25519/src/ed25519/ge_madd.o
11:28:40.762 [pimatic, ppm] info:   CC(target) Release/obj.target/ed25519/src/ed25519/ge_add.o
11:28:41.033 [pimatic, ppm] info:   CC(target) Release/obj.target/ed25519/src/ed25519/ge_msub.o
11:28:41.187 [pimatic, ppm] info:   CC(target) Release/obj.target/ed25519/src/ed25519/ge_sub.o
11:28:41.432 [pimatic, ppm] info:   CC(target) Release/obj.target/ed25519/src/ed25519/ge_p1p1_to_p3.o
11:28:41.687 [pimatic, ppm] info:   CC(target) Release/obj.target/ed25519/src/ed25519/ge_p1p1_to_p2.o
11:28:41.937 [pimatic, ppm] info:   CC(target) Release/obj.target/ed25519/src/ed25519/ge_tobytes.o
11:28:42.204 [pimatic, ppm] info:   CC(target) Release/obj.target/ed25519/src/ed25519/fe_0.o
11:28:42.459 [pimatic, ppm] info:   CC(target) Release/obj.target/ed25519/src/ed25519/fe_1.o
11:28:42.708 [pimatic, ppm] info:   CC(target) Release/obj.target/ed25519/src/ed25519/fe_cmov.o
11:28:48.679 [pimatic, ppm] info:   CC(target) Release/obj.target/ed25519/src/ed25519/fe_copy.o
11:28:53.038 [pimatic, ppm] info:   CC(target) Release/obj.target/ed25519/src/ed25519/fe_neg.o
11:28:53.218 [pimatic, ppm] info:   CC(target) Release/obj.target/ed25519/src/ed25519/fe_add.o
11:28:53.428 [pimatic, ppm] info:   CC(target) Release/obj.target/ed25519/src/ed25519/fe_sub.o
11:28:53.708 [pimatic, ppm] info:   CC(target) Release/obj.target/ed25519/src/ed25519/fe_mul.o
11:29:07.932 [pimatic, ppm] info:   CC(target) Release/obj.target/ed25519/src/ed25519/fe_sq.o
11:29:20.421 [pimatic, ppm] info:   CC(target) Release/obj.target/ed25519/src/ed25519/fe_sq2.o
11:29:21.967 [pimatic, ppm] info:   CC(target) Release/obj.target/ed25519/src/ed25519/fe_invert.o
11:29:22.365 [pimatic, ppm] info:   CC(target) Release/obj.target/ed25519/src/ed25519/fe_tobytes.o
11:29:24.167 [pimatic, ppm] info:   CC(target) Release/obj.target/ed25519/src/ed25519/fe_isnegative.o
11:29:24.414 [pimatic, ppm] info:   CC(target) Release/obj.target/ed25519/src/ed25519/fe_isnonzero.o
11:29:24.663 [pimatic, ppm] info:   CC(target) Release/obj.target/ed25519/src/ed25519/fe_frombytes.o
11:29:25.403 [pimatic, ppm] info:   CC(target) Release/obj.target/ed25519/src/ed25519/fe_pow22523.o
11:29:25.730 [pimatic, ppm] info:   CC(target) Release/obj.target/ed25519/src/ed25519/sc_reduce.o
11:29:29.855 [pimatic, ppm] info:   CC(target) Release/obj.target/ed25519/src/ed25519/sc_muladd.o
11:29:38.878 [pimatic, ppm] info:   CXX(target) Release/obj.target/ed25519/src/ed25519.o
11:29:43.456 [pimatic, ppm] info:   SOLINK_MODULE(target) Release/obj.target/ed25519.node
11:29:43.972 [pimatic, ppm] info:   COPY Release/ed25519.node
11:29:44.009 [pimatic, ppm] info: make: Leaving directory '/home/pi/pimatic-app/node_modules/pimatic-hap/node_modules/hap-nodejs/node_modules/ed25519/build'
11:29:44.047 [pimatic, ppm] info: > mdns@2.3.3 install /home/pi/pimatic-app/node_modules/pimatic-hap/node_modules/hap-nodejs/node_modules/mdns
11:29:44.051 [pimatic, ppm] info: > node-gyp rebuild
11:29:47.646 [pimatic, ppm] info: make: Entering directory '/home/pi/pimatic-app/node_modules/pimatic-hap/node_modules/hap-nodejs/node_modules/mdns/build'
11:29:47.650 [pimatic, ppm] info:   CXX(target) Release/obj.target/dns_sd_bindings/src/dns_sd.o
11:29:48.052 [pimatic, ppm] info: In file included from ../src/dns_sd.cpp:1:0:
11:29:48.053 [pimatic, ppm] info: ../src/mdns.hpp:32:20: fatal error: dns_sd.h: Datei oder Verzeichnis nicht gefunden
11:29:48.055 [pimatic, ppm] info:  #include <dns_sd.h>
11:29:48.058 [pimatic, ppm] info:                     ^
11:29:48.068 [pimatic, ppm] info: compilation terminated.
11:29:50.407 [pimatic, ppm] info: dns_sd_bindings.target.mk:142: recipe for target 'Release/obj.target/dns_sd_bindings/src/dns_sd.o' failed
11:29:50.415 [pimatic, ppm] info: make: Leaving directory '/home/pi/pimatic-app/node_modules/pimatic-hap/node_modules/hap-nodejs/node_modules/mdns/build'
11:29:50.418 [pimatic, ppm] info: make: *** [Release/obj.target/dns_sd_bindings/src/dns_sd.o] Error 1
11:29:50.431 [pimatic, ppm] info: gyp ERR! build error 
11:29:50.447 [pimatic, ppm] info: gyp ERR! stack Error:`make`failed with exit code: 2
11:29:50.456 [pimatic, ppm] info: gyp ERR! stack     at ChildProcess.onExit (/home/pi/pimatic-app/node_modules/pimatic/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
11:29:50.459 [pimatic, ppm] info: gyp ERR! stack     at emitTwo (events.js:87:13)
11:29:50.461 [pimatic, ppm] info: gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
11:29:50.464 [pimatic, ppm] info: gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
11:29:50.467 [pimatic, ppm] info: gyp ERR! System Linux 4.4.11-v7+
11:29:50.485 [pimatic, ppm] info: gyp ERR! command "/usr/bin/nodejs" "/home/pi/pimatic-app/node_modules/pimatic/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
11:29:50.488 [pimatic, ppm] info: gyp ERR! cwd /home/pi/pimatic-app/node_modules/pimatic-hap/node_modules/hap-nodejs/node_modules/mdns
11:29:50.492 [pimatic, ppm] info: gyp ERR! node -v v4.4.5
11:29:50.495 [pimatic, ppm] info: gyp ERR! node-gyp -v v3.3.1
11:29:50.500 [pimatic, ppm] info: gyp ERR! not ok 
11:29:50.506 [pimatic, ppm] info: > bignum@0.12.5 install /home/pi/pimatic-app/node_modules/pimatic-hap/node_modules/hap-nodejs/node_modules/srp/node_modules/bignum
11:29:50.509 [pimatic, ppm] info: > node-pre-gyp install --fallback-to-build
11:29:53.429 [pimatic, ppm] info: node-pre-gyp ERR! Tried to download: https://rvagg-node.s3-us-west-2.amazonaws.com/bignum/v0.12.5/bignum-v0.12.5-node-v46-linux-arm.tar.gz 
11:29:53.434 [pimatic, ppm] info: node-pre-gyp ERR! Pre-built binaries not found for bignum@0.12.5 and node@4.4.5 (node-v46 ABI) (falling back to source compile with node-gyp) 
11:29:58.930 [pimatic, ppm] info: make: Entering directory '/home/pi/pimatic-app/node_modules/pimatic-hap/node_modules/hap-nodejs/node_modules/srp/node_modules/bignum/build'
11:29:58.943 [pimatic, ppm] info:   CXX(target) Release/obj.target/bignum/bignum.o
11:30:12.511 [pimatic, ppm] info:   SOLINK_MODULE(target) Release/obj.target/bignum.node
11:30:12.809 [pimatic, ppm] info:   COPY Release/bignum.node
11:30:12.831 [pimatic, ppm] info:   COPY /home/pi/pimatic-app/node_modules/pimatic-hap/node_modules/hap-nodejs/node_modules/srp/node_modules/bignum/binding/bignum.node
11:30:12.854 [pimatic, ppm] info:   TOUCH Release/obj.target/action_after_build.stamp
11:30:12.866 [pimatic, ppm] info: make: Leaving directory '/home/pi/pimatic-app/node_modules/pimatic-hap/node_modules/hap-nodejs/node_modules/srp/node_modules/bignum/build'
11:30:12.924 [pimatic, ppm] info: ERR! Linux 4.4.11-v7+
11:30:12.928 [pimatic, ppm] info: ERR! argv "/usr/bin/nodejs" "/home/pi/pimatic-app/node_modules/pimatic/ppm.js" "install" "pimatic-hap@0.7.0" "--unsafe-perm"
11:30:12.936 [pimatic, ppm] info: ERR! node v4.4.5
11:30:12.937 [pimatic, ppm] info: ERR! npm  v2.15.6
11:30:12.939 [pimatic, ppm] info: ERR! code ELIFECYCLE
11:30:12.949 [pimatic, ppm] info: ERR! mdns@2.3.3 install:`node-gyp rebuild`
11:30:12.953 [pimatic, ppm] info: ERR! Exit status 1
11:30:12.954 [pimatic, ppm] info: ERR! 
11:30:12.956 [pimatic, ppm] info: ERR! Failed at the mdns@2.3.3 install script 'node-gyp rebuild'.
11:30:12.957 [pimatic, ppm] info: ERR! This is most likely a problem with the mdns package,
11:30:12.959 [pimatic, ppm] info: ERR! not with npm itself.
11:30:12.961 [pimatic, ppm] info: ERR! Tell the author that this fails on your system:
11:30:12.962 [pimatic, ppm] info: ERR!     node-gyp rebuild
11:30:12.964 [pimatic, ppm] info: ERR! You can get information on how to open an issue for this project with:
11:30:12.965 [pimatic, ppm] info: ERR!     npm bugs mdns
11:30:12.967 [pimatic, ppm] info: ERR! Or if that isn't available, you can get their info via:
11:30:12.991 [pimatic, ppm] info: ERR! 
11:30:12.994 [pimatic, ppm] info: ERR!     npm owner ls mdns
11:30:12.996 [pimatic, ppm] info: ERR! There is likely additional logging output above.
11:30:18.180 [pimatic, ppm] info: ERR! Please include the following file with any support request:
11:30:18.204 [pimatic, ppm] info: ERR!     /home/pi/pimatic-app/npm-debug.log
11:30:18.264 [pimatic] error: Error running "./node_modules/pimatic/ppm.js install pimatic-hap@0.7.0 --unsafe-perm"`

**Comment by michbeck100** [comment]
```
[pimatic, ppm] info: ../src/mdns.hpp:32:20: fatal error: dns_sd.h: Datei oder Verzeichnis nicht gefunden
```

Make sure to follow the installation instructions of pimatic-hap. It seems you missed

```
sudo apt-get install libnss-mdns libavahi-compat-libdnssd-dev
```

**Comment by michbeck100** [comment]
The other error about bignum did happen to me too. Seems seems that the download location isn't reliable. Just try again.

**Comment by HarrySteff** [comment]
Seems to be working now.... Sorry for this... Thank you so much!
