### ISSUE TITLE
Cannot find module 'hap-nodejs/node_modules/debug'

### ISSUE THREAD

**Issue by Timvdv** [michbeck100/pimatic-hap#41]
For some reason I'm unable to install Pimatic-HAP. I tried doing a fresh Pimatic install and I still get this error: `Cannot find module 'hap-nodejs/node_modules/debug'`

Any idea what this could be?

Ubuntu version:

```
3.13.0-88-generic #135-Ubuntu SMP Wed Jun 8 21:10:42 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

Screenshot of the error:
![schermafbeelding 2016-09-12 om 21 17 08](https://cloud.githubusercontent.com/assets/979227/18449251/c143656a-792e-11e6-8cc2-77bf36afb6c1.png)

In addition to this I tried installing it manually but then I get:

```
tim@Tim-server:~/pimatic-test/node_modules/pimatic-hap$ npm install debug
pimatic-hap@0.8.0 /home/tim/pimatic-test/node_modules/pimatic-hap
├── debug@2.2.0
└── UNMET PEER DEPENDENCY pimatic@~0.9.0

npm WARN pimatic-hap@0.8.0 requires a peer of pimatic@~0.9.0 but none was installed.
npm WARN pimatic-hap@0.8.0 No license field.
```

**Comment by michbeck100** [comment]
Please try to install again using the command line from the pimatic-hap folder in node_modules. I'm not sure but it might be a temporary problem with the download source

**Comment by michbeck100** [comment]
Please try to install again using the command line from the pimatic-hap folder in node_modules. I'm not sure but it might be a temporary problem with the download source. Maybe you have to delete the node_modules folder in pimatic-hap before.

**Comment by Timvdv** [comment]
Thanks for the response. Tried installing it again, got the same error when starting Pimatic. But during the installation process something caught my attention. Hope this clears things up.

```
> bignum@0.12.5 install /home/tim/pimatic-test/node_modules/bignum
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download: https://rvagg-node.s3-us-west-2.amazonaws.com/bignum/v0.12.5/bignum-v0.12.5-node-v47-linux-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for bignum@0.12.5 and node@5.10.1 (node-v47 ABI) (falling back to source compile with node-gyp)
make: Entering directory `/home/tim/pimatic-test/node_modules/bignum/build'
  CXX(target) Release/obj.target/bignum/bignum.o
  SOLINK_MODULE(target) Release/obj.target/bignum.node
  COPY Release/bignum.node
  COPY /home/tim/pimatic-test/node_modules/bignum/binding/bignum.node
  TOUCH Release/obj.target/action_after_build.stamp
make: Leaving directory `/home/tim/pimatic-test/node_modules/bignum/build'

> sqlite3@3.1.4 install /home/tim/pimatic-test/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build
```

**Comment by michbeck100** [comment]
I definitely had the same error. Another install solved this. Have no idea why it's not working always. Please try again. Sorry but this is the only solution I know for now

**Comment by Timvdv** [comment]
@michbeck100 Thanks for your help. What I did to fix this was just cloning directly from github into the node_modules folder then rm the git files and run npm install!

It's working great with the IOS10 home app. Best way to control my home now!
