### ISSUE TITLE
 Using Pimatic-Hap with pimatic-milight-reloaded

### ISSUE THREAD

**Issue by dermarder** [michbeck100/pimatic-hap#45]
Hello, first of all thank you very much for this awesome plugin!

I have a question: is it possible to use pimatic-hap with pimatic-milight-reloaded?

Thanks and regards
Tom

**Comment by michbeck100** [comment]
Implementing dimming and switching would be easy. Changing colors would take more effort. For the time being, you could use pimatic-led-light, which is already supported.

**Comment by michbeck100** [comment]
@dermarder a9dc842915ed5c39ca9a9a4e5b757135e9b284fe adds support for changing the hue value of milight devices. Could you please test if the changes work? Note that you have to install the plugin from https://github.com/michbeck100/pimatic-hap/tree/milight-reloaded as described [here](https://forum.pimatic.org/topic/1114/updated-how-to-install-a-plugin-from-github-using-npm-or-git).

**Comment by michbeck100** [comment]
@dermarder Did you test the changes?

**Comment by michbeck100** [comment]
Changes are released with v0.10.0

**Comment by Maple-Tears** [comment]
Does the _extended support for Milight devices_ also support the option to change the colors? I have an iBox2 in combination with an RGBW led strip controller, but I'm only able to change the brightness within Homekit. In Pimatic itself I can change the brightness and the colors of the strip.

**Comment by michbeck100** [comment]
I guess so, yes. As i don't own any of the milight supported devices, i can't really test, but in theory they should work. Maybe you can ask on the pimatic forum if anybody is using this device with homekit.
