### ISSUE TITLE
[pimatic-hap]: Could not call promise: timeout_error

### ISSUE THREAD

**Issue by tomvo** [michbeck100/pimatic-hap#46]
I have running hap now for the past week without any issues but since two days, whenever I try to fetch any data from an iOS device, I see this error in the pimatic logs. Any idea?

**Comment by michbeck100** [comment]
I would need more context. Just the error message is not not enough. Please post your error message and the surrounding lines of the log file, starting from the fetch request.

**Comment by tomvo** [comment]
thanks for your quick reply! the past two hours I fiddled around with the sensors and I noticed that my DHT22 also gave checksum errors once in a while. I replaced the resistor and the checksum errors were gone as well as the timeout_errors in the HAP library.
So thanks for your efforts but the issue seems solved!
