### ISSUE TITLE
Status indication of dimming devices in iphone home app

### ISSUE THREAD

**Issue by rspaargaren** [michbeck100/pimatic-hap#47]
Thanks for the support so far, the dimming devices are now working well within the home app. :-) Now the next observation. The dimming devices are shown as ON with the latest dimming % even though they are switched off via pimatic.
I think this has to do with the two ways of switching the lamps OFF.
- Sliding the slider to 0 via pimatic. -> Need to check what the indication in home app is.
- Sending the OFF signal via a rule within pimatic.
  As I use the last option for at least one of my devices I think that is the case.

I will test some more upon this for debug input...

**Comment by michbeck100** [comment]
The states (on/off for switches and dim level for dimmers) should always be in sync between pimatic and the home app. It doesn't matter how it's changed, if via rule or ui or anything else.

**Comment by rspaargaren** [comment]
The switches are indeed always in sync... issue closed. In the early Days I have programmed both a switch and a dimmer for the same device.... turning on with dimmer and turning off with the switch. Don't ask me why...:-)
