### ISSUE TITLE
Remove devices from homekit bridge when removed from pimatic

### ISSUE THREAD

**Issue by michbeck100** [michbeck100/pimatic-hap#50]
When removing devices from pimatic, they are not removed from homekit. Currently pimatic must be restarted.

**Comment by michbeck100** [comment]
Implemented with 845721ac6c2e3ab7c5212613bd64414217f78282

**Comment by pplucky** [comment]
Is it just me, or this still doesn't work properly?

Every time I remove a device in Pimatic, is still appears as not responding in Home app. If I try to delete it from there, I always get an error message.

What can I arrange (logs, whatever), for you to check this, please?

Thanks in advance.
