### ISSUE TITLE
Cannot find module '../build/Release/dns_sd_bindings'

### ISSUE THREAD

**Issue by PJCzx** [michbeck100/pimatic-hap#52]
@michbeck100,

Hello ! First, thanks a lot for your work. I seen the update from this afternoon, after installing it from the Pimatic UI I have this message:

```
 [pimatic] Cannot find module '../build/Release/dns_sd_bindings'
```

Do you have an idea on the issue ? 

Thx a lot
PJ

**Comment by michbeck100** [comment]
Did you install the dependencies as stated here: https://github.com/michbeck100/pimatic-hap#installation?

**Comment by PJCzx** [comment]
I'm about to do it again but I updated from the previous version who was working. Keep you informed ;)

**Comment by michbeck100** [comment]
If normal update doesn't work for you just delete the pimatic-hap folder under node_modules and restart pimatic. It will install the latest version automatically

**Comment by PJCzx** [comment]
Yep, deleting and re run solved the issue :) THX

Btw, I work on [windowCover service for Homebridge](https://github.com/PJCzx/homebridge-window-cover) but I'm quite seduce by Pimatic and I'm looking for an angle. Any insight ? 

Thx again.
PJ
