### ISSUE TITLE
Reducing thermostat temperature steps

### ISSUE THREAD

**Issue by LeopoldKing** [michbeck100/pimatic-hap#59]
Hi,

is there any chance to reduce the steps from 1 degree to 0.5 degrees? 

Cheers.

**Comment by michbeck100** [comment]
it seems that at least the Apple Home app just has steps of 1 degree. Thats nothing pimatic-hap can influence. Nevertheless pimatic itself supports 0.5 degrees step and Siri even supports 0.1 steps. You just can't  use the slider from the home app.
