### ISSUE TITLE
Invalid config of device "woonkamer": Missing property "service" in /hap

### ISSUE THREAD

**Issue by Timvdv** [michbeck100/pimatic-hap#61]
All devices result in `Missing property "service" in /hap` on startup.

![schermafbeelding 2017-01-02 om 21 42 39](https://cloud.githubusercontent.com/assets/979227/21596013/3fec3ca8-d135-11e6-8596-091cbd61c925.png)

Is this a config issue on my side or a bug in the plugin?

**Comment by michbeck100** [comment]
Neither nor. It's more like a warning. I'm currently working on a pull request for pimatic that this error is gone

**Comment by Timvdv** [comment]
Ahh cool! I'll just ignore these than. Thanks for the quick reply 😄
