### ISSUE TITLE
uncaught exception related to pimatic-hap

### ISSUE THREAD

**Issue by pplucky** [michbeck100/pimatic-hap#63]
As far as I remember, pimatic-hap was not working properly and communicating to Homekit. A reboot to Pimatic made it work again.

`error [pimatic]: A uncaught exception occured: Error: dns service error: unknown at Error (native) at Advertisement.on_service_registered (/home/pi/pimatic-app/node_modules/pimatic-hap/node_modules/hap-nodejs/node_modules/mdns/lib/advertisement.js:42:24) at SocketWatcher.MDNSService.self.watcher.callback (/home/pi/pimatic-app/node_modules/pimatic-hap/node_modules/hap-nodejs/node_modules/mdns/lib/mdns_service.js:18:40) This is most probably a bug in pimatic or in a module, please report it!`

Opened as issue [#1051](https://github.com/pimatic/pimatic/issues/1051) in pimatic github, but requested to open it here instead.

**Comment by michbeck100** [comment]
This is not an error I can fix in pimatic-hap. Please refer to all the issues raised already:
https://github.com/nfarina/homebridge/issues/613
https://github.com/agnat/node_mdns/issues/104
https://github.com/nfarina/homebridge/issues/899
https://github.com/KhaosT/HAP-NodeJS/issues/367

These are just some of the search results I found when searching for "dns service error: unknown"
