### ISSUE TITLE
Q: Does pimatic-hap plugin require node.js 4.3 to run?

### ISSUE THREAD

**Issue by mwittig** [michbeck100/pimatic-hap#66]
I heard rumors some of the submodules of the pimatic-hap plugin require node 4.3. Is this still the case? 

https://forum.pimatic.org/topic/2904/using-nodejs-7-x/3

**Comment by georg90** [comment]
I can confirm that using node 4.8 it worked (after manually running `npm install` inside `pimatic-hap`)

Using 4.2.X I only got several errors..

**Comment by michbeck100** [comment]
As @georg90 wrote, node v4 is supported, that includes 4.8.0 as well. 
@mwittig it might be that this was the case at some point, but the current dependencies are working with this version.
