### ISSUE TITLE
Q: Does this work on iOS 9 using Eve?

### ISSUE THREAD

**Issue by georg90** [michbeck100/pimatic-hap#67]
There is an extra eve app called "Eve for iOS 9" - but when I install it & search for devices I cannot find my pimatic homekit bridge. 

It's working fine with Apple's Home app on iOS 10.

Any ideas?

**Comment by michbeck100** [comment]
No ideas. Sorry. pimatic-hap runs against the most recent version of HomeKit. And this is for iOS 10. I'm sorry that i have to say that you must do the upgrade to iOS 10.

**Comment by georg90** [comment]
yeah, not possible for ipad mini 1 ;)
Thanks anyway!
