### ISSUE TITLE
error [pimatic]: A uncaught exception occured: Error: dns service error: unknown

### ISSUE THREAD

**Issue by mwittig** [michbeck100/pimatic-hap#69]
Can you please have a look at https://github.com/pimatic/pimatic/issues/1062

The issue seem to be related to the MDNS socket watcher. Possibly it is a problem with avahi daemon not running or setup properly?!

**Comment by michbeck100** [comment]
Please see https://github.com/michbeck100/pimatic-hap/issues/10
