### ISSUE TITLE
Add null to the line

### ISSUE THREAD

**Issue by rspaargaren** [michbeck100/pimatic-hap#7]
Hi I am just reading your code, not based on any direct error just by comparing... Should there not be null added to the end of line 157 of hap.coffee? I compared it with line 190. A bulb is the same as a switch?

**Comment by michbeck100** [comment]
If omitting the last parameter (which is the optional converter callback) it will be just undefined. This is checked by 'if converter' in line 106. 
But to be honest I'm not a JS pro, so I could be wrong

**Comment by rspaargaren** [comment]
Are you not introducing an error if you leave it undefined as mentioned in issue #138? Better safe then sorry...

I had exactly the same console output after adding a new accessory type. It took me a while to figure out why all the accessories greyed out after restart or after the phone was out of the local network for a while.  In the end it was a characteristic that returned "undefined" when queried due to a bug.
 After solving the issue, everything works fine again.

**Comment by michbeck100** [comment]
You are probably right. Since i don't feel like checking for null and undefined all the time i call the method rather using all parameters. Thanks for your hint!
