### ISSUE TITLE
Cannot find module 'hap-nodejs/node_modules/debug'

### ISSUE THREAD

**Issue by Calprainn** [michbeck100/pimatic-hap#72]
After a fresh install of pimatic (on Ubuntu 16.04.2 LTS) I tried to install pimatic-hap (and get the follow message):

```
npm install pimatic-hap
/calprainn/pimatic-app
└── pimatic-hap@0.10.0

npm WARN enoent ENOENT: no such file or directory, open '/root/pimatic-app/package.json'
npm WARN pimatic-app No description
npm WARN pimatic-app No repository field.
npm WARN pimatic-app No README data
npm WARN pimatic-app No license field.
```

When I restart pimatic I got this error message:
`error [pimatic]: Cannot find module 'hap-nodejs/node_modules/debug'`

The debug option is turned OFF in the plugin settings of pimatic-hap.

Any ideas?

**Comment by michbeck100** [comment]
Please checkif the folder node_modules/pimatic-hap/node_modules/hap-nodejs/node_modules/debug in your pimatic-app folder exists. If not please remove the complete pimatic-hap folder from node_modules and restart pimatic. It should start a new install then.

**Comment by Calprainn** [comment]
For whatever reason, the debug folder wasn't there. I remove and reinstall hap-nodejs ("npm install hap-nodejs") and cloning pimatic-app from github both into the node_modules folder and run "npm install" by both. After restart pimatic-hap runs like a charm. Thanks!! :)
