### ISSUE TITLE
[Feature request] Please support Netatmo rain and wind gauge

### ISSUE THREAD

**Issue by osxdoc** [michbeck100/pimatic-hap#77]
Homebridge supports the wind and rain gauge in the "Eve"-App in iOS
https://www.npmjs.com/package/homebridge-netatmo

"The rain gauge and the wind gauge are in general supported, but these devices use characteristics, which are not supported by the home app.

For this reason the home app shows the devices as not supported. If you want to use this devices you should consider to use a different homekit app. For example elgato's eve app is a good free alternative."

Please support in pimatic-hap, too.

**Comment by michbeck100** [comment]
As stated on https://github.com/planetk/homebridge-netatmo/issues/25 these sensors are not officially supported by Apple HomeKit. As I'm using [hap-nodejs](https://github.com/KhaosT/HAP-NodeJS) to expose the pimatic devices to HomeKit, and hap-nodejs just includes the officially supported device types, there will unfortunately be no support for this, as long as Apple doesn't include them in HomeKit, too. Sorry.
