### ISSUE TITLE
v0.12.0 - plugin does not start

### ISSUE THREAD

**Issue by 00lex** [michbeck100/pimatic-hap#82]
hi mich,
something happens after your last update. following section is removed from all devices:
<img width="1641" alt="Bildschirmfoto 2019-07-15 um 23 45 15" src="https://user-images.githubusercontent.com/39100562/61251555-105e7880-a75b-11e9-8b3a-cc010c878c79.png">

as a result I get 50+ error messages on every restart. I know I can ignore this, but it doesnt look good. I miss the overview on important logs.

even if I delete and add a device this option is missing

**Comment by michbeck100** [comment]
did you install the latest updates, too? Because from 0.11.2 to 0.12.0 there wasn't any change regarding this behaviour.

**Comment by michbeck100** [comment]
I would say that the plugin didn't start correctly, or it was moved to the end of the plugins section of your config. It must be at the beginning, like pimatic-echo, otherwise the hap section isn't registered with the pimatic framework.

**Comment by 00lex** [comment]
yes I come from 0.11.2. 

with 0.11.2 and the four addition lines 
```
      'raspbee-dimmer': DimmerAccessory
      'raspbee-ct': DimmerAccessory
      'raspbee-rgb': HueLightAccessory
      'raspbee-rgbct': HueLightAccessory
```
everything works. I have nothing changed, but after update hap plugin doesnt start correct and pimatic produce the mentioned errors. 

 I think something goes wrong while update. when I start pimatic manual I see the debug folder is missing:
<img width="761" alt="Bildschirmfoto 2019-07-16 um 12 24 14" src="https://user-images.githubusercontent.com/39100562/61287211-aaa6d680-a7c4-11e9-94bb-c82a54b0fef6.png">

if I copy this folder from my old instance, hap works, but with other error messages. anyway..

I try to instal hap manual:
`sudo npm install --unsafe-perm pimatic-hap`
with the same result. missing debug folder and "Property "hap" is not a valid property" errors.

please forgive the circumstances. but i can't be the only one with this problem. or maybe yes :( 
for the moment I will stay on 0.11.2. with the modified _hap.coffee_

here my install log: https://pastebin.com/raw/kh3k1QQW

**Comment by michbeck100** [comment]
I see. You are using a node version that isn't officially supported by pimatic-hap. But I will try to fix this.

**Comment by michbeck100** [comment]
Please try with 0.12.1

**Comment by 00lex** [comment]
YES! now with v0.12.1 everything woks as expected. Thank you for the quick fix
