### ISSUE TITLE
Support for RaspBeeMultiDevice (Aqara door/window sensors)

### ISSUE THREAD

**Issue by sebster6** [michbeck100/pimatic-hap#85]
I added a couple of Zigbee door/window sensors (Xiaomi / Aqara) using the pimatic-raspbee (and the USB Zigbee dongle). They work fine within Pimatic, showing open/close state, battery level and temperature.
Unfortunately, only the temperature value seems to be provided to HomeKit by pimatic-hap. Any chance to add the parameters from the RaspBeeMultiSensor (https://github.com/treban/pimatic-raspbee/blob/master/README.md#pimatic-raspbee), maybe the open/close state as a start? ;)

Thanks in advance!
![IMG_1881](https://user-images.githubusercontent.com/9269030/74842263-66675000-532a-11ea-85d8-7e534625859d.png)
![IMG_1882](https://user-images.githubusercontent.com/9269030/74842267-68311380-532a-11ea-99dc-cf374378fca5.png)

**Comment by michbeck100** [comment]
Fixed with https://github.com/michbeck100/pimatic-hap/pull/83

**Comment by theslash** [comment]
Works perfectly, thank you very much!!
